check50:
  files: &check50_files
    - !exclude "*"
    - !require Diamond.java
  checks:
    hello world:
      - run: java Diamond.java
        stdout:    D
        exit: 0

submit50:
  files: *check50_files
