check50:
  files: &check50_files
    - !exclude "*"
    - !require Diamond.java
  checks:
    hello world:
      - run: java Diamond.java
        stdout:    D\n  I I\n A   A\nM     M\n O   O\n  N N\n   D\n
        exit: 0

submit50:
  files: *check50_files
