check50:
  files: &check50_files
    - !exclude "*"
    - !require PetTest.java
  checks:
    diamond:
      - run: javac PetTest.java
        run: java PetTest.java
        stdout: Fido\nPolly\nTiger\n
        exit: 0

submit50:
  files: *check50_files
