check50:
  files: &check50_files
    - !exclude "*"
    - !require Pet.java
  checks:
    PetTest:
      - run: java Pet.java
        stdout: Fido\nPolly\nTiger\n
        exit: 0

submit50:
  files: *check50_files
