check50:
  files: &check50_files
    - !exclude "*"
    - !require DigitSum.java
  checks:
    digit sum 932 is 14:
      - run: java DigitSum.java
        stdin: 932
        stdout: 14
        exit: 0

submit50:
  files: *check50_files
