check50:
  checks:
    digit sum 932 is 14:
      - run: java DigitSum.java
        stdin: 932
        stdout: 14
        exit: 0
    digit sum 93 is 12:
      - run: java DigitSum.java
        stdin: 93
        stdout: 12
        exit: 0
    digit sum 0 is 0:
      - run: java DigitSum.java
        stdin: 0
        stdout: 0
        exit: 0
    digit sum -932 is -14:
      - run: java DigitSum.java
        stdin: -932
        stdout: -14
        exit: 0
